---
title: "Publications"
---
***  
  
**Simeon, K.M.**, Bicknell, K., & Grieco-Calub, T.M. (2018). Belief shift or only facilitation: how semantic expectancy affects processing of speech degraded by background noise, *Frontiers in Psychology*. 9:116. doi: 10.3389/fpsyg.2018.00116 [[pdf](files/2018_Context_Frontiers.pdf)]  
  \    
Grieco-Calub, T.M., **Simeon, K.M.**, Snyder, H.E., & Lew-Williams, C. (2017). Word segmentation from noise-band vocoded speech, *Language, Cognition and Neuroscience*. 32:10, 1344-1356. doi: 10.1080/23273798.2017.1354129 [[pdf](files/2017_Vocoded_LCN.pdf)] 
  
***  
### Conference Presentations  
  
**Simeon, K.M.** & Grieco-Calub, T.M. (2018). *Effects of speech competitors on encoding features of novel word-object pairs*. Poster presented at the 175rd Meeting of the Acoustical Society of America, Minneapolis, MN, May 2018. [[poster](files/2018_ASA_Simeon_et_TGC.pdf)]     
  
**Simeon, K.M.**, Bicknell, K., & Grieco-Calub, T.M. (2017). *The effect of hearing acuity on using semantic expectancy in degraded speech*. Poster presented at the 173rd Meeting of the Acoustical Society of America, Boston, MA, June 2017. [[poster](files/2017_ASA_Simeon_etal.pdf)]   
   
**Simeon, K.M.**, Bicknell, K., & Grieco-Calub, T.M. (2017). *Great Expectations: weighting expectancy when processing degraded speech*. Oral presentation at the 91st Annual Meeting of the Linguistic Society of America, Austin, TX, January 2017. [[talk materials](files/2017_LSA_Talk_SimeonEtAl.pdf)]     
  
**Simeon, K.M.**, Snyder, H.E., Lew-Williams, C., & Grieco-Calub, T.M. (2016). *Temporal information facilitates statistical learning of spectrally degraded speech*. Oral presentation at the 90th Annual Meeting of the Linguistic Society of America, Washington, DC, January 2016. [[talk materials](files/2016_LSA_Simeon_EtAl.pdf)]   
    
**Simeon, K.M.**, Snyder, H.E., Lew-Williams, C., & Grieco-Calub, T.M. (2015). *The effect of isolating words on segmenting noise-band vocoded speech*. Poster presented at the 68th Linguistic Society of America Linguistics Institute, Chicago, IL, July 2015. [[poster](files/2015_LSAInst_SimeonEtAl.pdf)]   
  
Atkinson, E., **Simeon, K.**, & Omaki, A. (2013). *The time course of the filler-gap dependency in the developing parser*. Poster presented at the 26th Annual CUNY Conference on Human Sentence Processing, Columbia, SC, March 2013.  [[poster](files/2013_cuny_atkinsonsimeonomaki.pdf)]
  


***    
  
See my [ResearchGate Profile](https://www.researchgate.net/profile/Katherine_Simeon)